language: "ja"
reviews:
  profile: "chill"
  high_level_summary: true
  poem: false
auto_review:
  enabled: true
  ignore_title_keywords:
    - "WIP"
    - "DO NOT MERGE"
  drafts: true
chat:
  auto_reply: true
