language: "ja"
reviews:
  profile: "detailed"
  high_level_summary: true
  poem: false
  comment_always: true
  focus_areas:
    - "architecture"
    - "performance"
    - "security"
    - "code_quality"
auto_review:
  enabled: true
  ignore_title_keywords:
    - "WIP"
    - "DO NOT MERGE"
  drafts: true
  comment_on_every_change: true
chat:
  auto_reply: true
